# Generated by Django 4.0.4 on 2022-06-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_residents_text_residents_text_en_residents_text_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='raqamlashtirishxizmalari',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raqamlashtirishxizmalari',
            name='category_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raqamlashtirishxizmalari',
            name='category_ru',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
